parameters:
#    football_news.example.class: Football\NewsBundle\Example

services:
#    football_news.example:
#        class: %football_news.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
